# Generated by Django 4.1.5 on 2023-01-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(default='media/image/bored-ape-yacht-club-bayc.jpg', upload_to='image/'),
        ),
    ]
