# Generated by Django 4.1.5 on 2023-01-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='titulo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
