# Generated by Django 4.1.5 on 2023-01-31 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_items_titulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='items',
        ),
    ]
