# Generated by Django 4.1.5 on 2023-02-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
