# Generated by Django 4.1.5 on 2023-02-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0006_foto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
