# Generated by Django 4.1.5 on 2023-02-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0007_alter_foto_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_user',
            name='foto',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='image/'),
        ),
    ]
