# Generated by Django 4.1.5 on 2023-02-09 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autor', '0009_delete_foto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguir',
            name='seguido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguido', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seguir',
            name='seguidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidor', to=settings.AUTH_USER_MODEL),
        ),
    ]
