# Generated by Django 4.1.5 on 2023-02-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
