# Generated by Django 4.1.5 on 2023-01-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField(max_length=50)),
                ('Preco', models.FloatField()),
                ('royalties', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
