# Generated by Django 4.1.5 on 2023-01-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='descricao',
            field=models.CharField(max_length=50),
        ),
    ]
