# Generated by Django 4.1.5 on 2023-01-29 05:35

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criar', '0009_alter_items_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='items',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
