# Generated by Django 4.1.5 on 2023-01-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criar', '0010_alter_items_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='usuario',
        ),
    ]
