# Generated by Django 4.1.5 on 2023-02-02 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criar', '0014_items_data_esírada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='data_esírada',
            new_name='data_espírada',
        ),
    ]
