# Generated by Django 4.1.5 on 2023-02-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criar', '0015_rename_data_esírada_items_data_espírada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='data_espírada',
            new_name='data_atual',
        ),
    ]
