# Generated by Django 4.1.5 on 2023-02-02 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criar', '0016_rename_data_espírada_items_data_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='data_vencimento',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
