# Generated by Django 4.1.5 on 2023-02-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criar', '0017_items_data_vencimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='data_vencimento',
        ),
    ]
