# Generated by Django 4.1.5 on 2023-02-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criar', '0018_remove_items_data_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='data_atual',
            field=models.DateTimeField(),
        ),
    ]
