# Generated by Django 4.1.5 on 2023-02-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criar', '0019_alter_items_data_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='titulo',
            field=models.CharField(max_length=19),
        ),
    ]
